ifndef HADOOP_VERSION
HADOOP_VERSION=1.2.1
endif

HADOOP_INSTALL=$(HOME)/Downloads/hadoop-$(HADOOP_VERSION)
#HADOOP_INSTALL=$(HOME)/Downloads/hadoop-2.2.0

JAVAC=javac
HADOOP_CLASSPATH=$(shell $(HADOOP_INSTALL)/bin/hadoop classpath)
JAVAC_FLAGS=-classpath .:$(HADOOP_CLASSPATH) -Xlint:deprecation

%.class: %.java
	$(JAVAC) $(JAVAC_FLAGS) $<


eg.jar: ArrivalDelayMapper.class ArrivalDelayReduce.class DelaysFrequencyTable.class
	jar cf $@ $^

run: eg.jar
	(export HADOOP_CLASSPATH=eg.jar ; hadoop DelaysFrequencyTable data Out)
#$(HADOOP_INSTALL)/bin/hadoop DelaysFrequencyTable Data Out)


clean:  
	rm *.class



#javac -classpath .:$HADOOP_HOME/hadoop-core-1.2.1.jar DelaysFrequencyTable.java

javac -classpath $HADOOP_HOME/hadoop-core-1.2.1.jar ArrivalDelayMapper.java
jar cvf eg.jar ArrivalDelayMapper.class ArrivalDelayReduce.class DelaysFrequencyTable.class
hadoop fs -rmr Out
make run

hadoop fs -copyToLocal Out/part* ./